services:
  speech-api:
    build:
      context: ./speech-api
      dockerfile: Dockerfile
    image: speech-api:latest
    container_name: speech-api
    ports:
      - "8000:8000"
    env_file:
      - ./speech-api/.env
    restart: unless-stopped
    volumes:
      - ./speech-api/uploads:/app/uploads
